### ISSUE TITLE
Enhancement request- Measurement widget

### ISSUE THREAD

**Issue by stopyaks** [Esri/tax-parcel-viewer#21]
I've had a lightly modified version of this app running for a while. The only real complaint I've gotten is that there's no measure tool. It would be great if it had one but I can't figure out how to do it.

**Comment by dbreeding** [comment]
@LindsayThomas, I've also received requests for measurement tools from users both inside and outside municipal government (Real Estate Brokers and DPW users).  Is there any hope for a measurement toolset in the future?  If not, would you still start your development efforts from the link you provided Oct 29th?  Is this a better option to start from? http://www.arcgis.com/home/item.html?id=91a0014160fc4a9caadc2c7fd7089c1b

**Comment by LindsayThomas** [comment]
@dbreeding If you wanted to add a measure tool then, yes, I would start with the URL from October 29th.    The link provided is referencing Flex. So, I would use use the starting point based on the technology you plan on using (JavaScript or Flex).

**Comment by dbreeding** [comment]
@LindsayThomas So it would be appropriate to assume you have no plans currently to develop the measurement tool functionality?

**Comment by ScottOppmann** [comment]
That is correct, we do not plan on adding a measure tool to the Tax Parcel Viewer.

**Comment by stopyaks** [comment]
Why not? There seems to be a decent amount of demand for it. Are you guys
planning to keep developing these github apps? There doesn't seem to be
much activity.

On Wed, Mar 4, 2015 at 6:50 PM, Scott Oppmann <notifications@github.com>
wrote:

> That is correct, we do not plan on adding a measure tool to the Tax Parcel
> Viewer.
>
> From: dbreeding [mailto:notifications@github.com]
> Sent: Wednesday, March 4, 2015 1:34 PM
> To: Esri/tax-parcel-viewer
> Subject: Re: [tax-parcel-viewer] Enhancement request- Measurement widget
> (#21)
>
>
> @LindsayThomas<https://github.com/LindsayThomas> So it would be
> appropriate to assume you have no plans currently to develop the
> measurement tool functionality?
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/Esri/tax-parcel-viewer/issues/21#issuecomment-77216830>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/tax-parcel-viewer/issues/21#issuecomment-77276881>
> .
>



-- 
*Scott Stopyak*

Email : *stopyak.*scott@gmail.com
Phone : (517) 315-9419

**Comment by ScottOppmann** [comment]
You may not see a whole lot of activity on an individual app, but we are continuously growing and evolving our ArcGIS for Local Government solution.  Here is a link to what’s new with each release:

http://solutions.arcgis.com/local-government/what-is-new/

The Tax Parcel Viewer was designed to be a consumer focused application that is primarily used on tablets and smartphones.  As such, we don’t believe a measure tool is appropriate in that use case.    We are working on plans now for a future version of the Tax Parcel Viewer – more info on that in the coming months.

**Comment by stopyaks** [comment]
Just saying. I know esri is working on some things and there's always
something new in the works. Caveat being, I think that when it comes to the
LGIM and its related maps and apps, that there's a ways to go before many
items are ready for production, but are instead left alone as "a good
start".  A "good start" is only useful if you have a really good
GIS/Javascript programmer which, unless you're in the rare Oakland County
type setting, doesn't happen that often for local governments. My advice,
for what its worth, is to slow down and quit rushing toward the next big
thing. Nobody is nipping at esri's heels. Take feedback from users a little
more seriously and continue to develop and improve these apps based on that
feedback. I've done beta testing for your web app builder and I'm not a
great javascript programmer but am trying to contribute,in some meaningful
way, to the development of apps like the parcel viewer. IMHO, there is good
responsiveness in terms of email correspondence but almost no resulting
development initiative. The last time it was even touched was 9 months ago
and that isn't because it is a perfect app on any platform. Case in point,
it just got technologically trumped by a yard stick. If there's a new one
in the works, clearly the old one is being phased out. Wouldn't it make
sense to have the new one on github or in the beta community? Wouldn't it
also make sense to be a little more forthcoming with the details of the
LGIMs development goals so that users, proponents and contributing
developers can go with the flow, so to speak, and don't waste a lot time on
apps that will soon be extinct?



On Thu, Mar 5, 2015 at 10:28 AM, Scott Oppmann <notifications@github.com>
wrote:

> You may not see a whole lot of activity on an individual app, but we are
> continuously growing and evolving our ArcGIS for Local Government solution.
> Here is a link to what’s new with each release:
>
> http://solutions.arcgis.com/local-government/what-is-new/
>
> The Tax Parcel Viewer was designed to be a consumer focused application
> that is primarily used on tablets and smartphones. As such, we don’t
> believe a measure tool is appropriate in that use case. We are working on
> plans now for a future version of the Tax Parcel Viewer – more info on that
> in the coming months.
>
> From: stopyaks [mailto:notifications@github.com]
> Sent: Thursday, March 5, 2015 9:21 AM
> To: Esri/tax-parcel-viewer
> Cc: Scott Oppmann
> Subject: Re: [tax-parcel-viewer] Enhancement request- Measurement widget
> (#21)
>
> Why not? There seems to be a decent amount of demand for it. Are you guys
> planning to keep developing these github apps? There doesn't seem to be
> much activity.
>
> On Wed, Mar 4, 2015 at 6:50 PM, Scott Oppmann <notifications@github.com>
> wrote:
>
> > That is correct, we do not plan on adding a measure tool to the Tax
> Parcel
> > Viewer.
> >
> > From: dbreeding [mailto:notifications@github.com]
> > Sent: Wednesday, March 4, 2015 1:34 PM
> > To: Esri/tax-parcel-viewer
> > Subject: Re: [tax-parcel-viewer] Enhancement request- Measurement widget
> > (#21)
> >
> >
> > @LindsayThomas<https://github.com/LindsayThomas> So it would be
> > appropriate to assume you have no plans currently to develop the
> > measurement tool functionality?
> >
> > —
> > Reply to this email directly or view it on GitHub<
> >
> https://github.com/Esri/tax-parcel-viewer/issues/21#issuecomment-77216830>.
>
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/Esri/tax-parcel-viewer/issues/21#issuecomment-77276881>
>
> > .
> >
>
>
>
> --
> *Scott Stopyak*
>
> Email : *stopyak.*scott@gmail.com
> Phone : (517) 315-9419
>
>
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/Esri/tax-parcel-viewer/issues/21#issuecomment-77370930>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/tax-parcel-viewer/issues/21#issuecomment-77383886>
> .
>



-- 
*Scott Stopyak*

Email : *stopyak.*scott@gmail.com
Phone : (517) 315-9419

**Comment by ScottOppmann** [comment]
We are very forthcoming and transparent with our development plans and just had a meetup in January to discuss all our plans for the first half of 2015.  If you aren’t participating in the meetups, I would encourage that.  It’s a great way to stay connected to the team and learn what is coming / how to leverage what already exists.  We record the meetups so you can watch them later if you’d like.

http://www.meetup.com/ArcGIS-for-Local-Government/

It’s still way too early in the dev process to share the next generation tax parcel viewer.  Honestly, we’re just now organizing our requirements/thoughts.  When we get more details organized, we’ll definitely share them.

It is difficult to move a large ship (local government GIS) in a quick and nimble way.  Our portfolio of solution offerings is quite large and we are constantly balancing new development vs. support of existing solutions.  We hear you loud and clear and will try to be more forthright on our plans to incorporate feedback so you can make development plans of your own.
