### ISSUE TITLE
Update to JS API 3.16+ request

### ISSUE THREAD

**Issue by ChuckBenton** [Esri/tax-parcel-viewer#34]
I need to use FeatureTable as used in 
https://developers.arcgis.com/javascript/3/jssamples/featuretable_custommenu.html. The featureTable functionality requlred is not available in 3.11, but is in 3.16+.

I've tried to get my variant of TaxParcelViewer running under 3.18.  

After changing references to 3.11 to 3.18, I’m getting the following error: Type Error: a.id.match is not a function.

I’ve been through Geonet and StackOverflow and not found anything helpful. 

I've been through this with an analyst without finding a solution (see case #01793500) 

So, an update by the solutions team is requested.

**Comment by LindsayThomas** [comment]
@ChuckBenton We are not planning an update of the API for this Tax Parcel Viewer at the moment.

What about trying to update to 3.16 instead of all the way to 3.18? Does that give a different result? 

(Also, I have updated API's in the default.htm's in the past and have had bizarre results if I do not update all the references of the API. I see three in the default.htm on line 24, 25, & 39.)

cc:@ChrisBuscaglia

**Comment by ChuckBenton** [comment]
Lindsay,

Thanks for getting back to me.  I tried 3.16 a couple months ago without luck, when the app was on AWS.  I then moved to Azure, and figured I’d revisit it after getting up on Azure.  That was a week or so ago, and the API had evolved to 3.18 at that time.

I get the same error in both cases, Type Error: a.id.match is not a function

Yes, I have updated all the references in default.htm.  

I get the impression that this error is a result of something deeper in the API than I am prepared to resolve myself.  That said, I really am dependent on using the FeatureTable functionality.  The alternative is to write a similar capability myself, which seems a waste of time since eventually the Tax Parcel Solution will need to be operable with the current ArcGIS development suite.

Could you try to update the solution to 3.18 and get a feel what what the proper approach to resolving this may be? Might it make sense for me to bring this to the JS API development team?  

Thanks in advance for any help you can provide!!

Chuck

**Comment by ChuckBenton** [comment]
FYI, I posted this on GeoNet, see https://geonet.esri.com/message/644364-js-api-error-upgrading-to-316-from-311

**Comment by ChuckBenton** [comment]
Found the fix, per my favorite ESRI analyst:
 
I tested it and I noticed that the issue is actually coming from the js/locator.js file in line 698, , acutally there is a code defect, since sometime map.getLayer(neighbourHoodLayerInfo[i].id) is undefined, and in  js api 3.11,it is not that sensitive, but in 3.18 it is more restrict on the code, so what you will need to do is just add another if statement outside of this if, so then it should look like this(I highlited the code that I added in line 697) :
line 696        for (var i in neighbourHoodLayerInfo) {
line 697                        if (neighbourHoodLayerInfo.hasOwnProperty(i)**&&map.getLayer(neighbourHoodLayerInfo[i].id)**) {
line 698                                  if (map.getLayer(neighbourHoodLayerInfo[i].id).maxScale <= ((mapScale) ? mapScale :              
                                                  Number(dojo.byId("divShareContainer").getAttribute("mapScale"))) &&                      
                                                  map.getLayer(neighbourHoodLayerInfo[i].id).minScale >= ((mapScale) ? mapScale :
                                                   Number(dojo.byId("divShareContainer").getAttribute("mapScale")))) {
line 699                         PopulateNeighbourHoodInformation(neighbourHoodLayerInfo[i], mapPoint, null);
            }
        }
    }

**Comment by LindsayThomas** [comment]
@ChuckBenton Thanks for you sharing the solution with the community. It is also, nice to hear you have a favorite Esri Support Analyst.
